spring:
  application:
    name: demo
  datasource:
    url: ${DBMS_CONNECTION:jdbc:postgresql://localhost:5432/elearning_db}
    username: ${DBMS_USERNAME:postgres}
    password: ${DBMS_PASSWORD:250104}
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format-sql: true
  session:
    store-type: jdbc
    timeout: 10m
    jdbc:
      initialize-schema: always
    cookie:
      name: my_cookie
      http-only: true
      secure: true
  cache:
    type: redis

  data:
    redis:
      host: localhost
      port: 6379

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    prometheus:
      enabled: true
#  security:
#    user:
#      name: chuong
#      password: 123456